name: password_policy
description: Dart package that help restrict passwords to a strong policy.
version: 1.0.0
homepage: https://github.com/Milvintsiss/password_policy
repository: https://github.com/Milvintsiss/password_policy
issue_tracker: https://github.com/Milvintsiss/password_policy/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  dart_code_metrics: ^4.10.1
#  test: ^1.16.0
